/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package krithikha;


import com.toedter.calendar.JMonthChooser;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;



/**
 *
 * @author krithikha
 */
public  class checkout extends javax.swing.JPanel {
 
      
    Connection con;
    void opencon(){
        try{
            Class.forName("java.sql.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/hotel","root","pass");
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        }
    Date cdt;
      void chkout(){ 
          try{
            DateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
        String d1 = fmt.format(this.dtc.getDate());    
      String rno= (String) cb.getSelectedItem();
      String type="";
       String flr="";
        String acond="";
         String vw="";
         String fn="";
         String ln="";
         String g="";
         int rpd=0;
         
        String q="Select * from rinfo natural join custinfo where custinfo.rno='"+rno+"' and 1status ='occupied'";             ///see anbout the status coloumn in rinfo table 
        
       Statement stmt =con.createStatement();
               ResultSet rs=stmt.executeQuery(q);               //do dtm.remove row also .oops no dont do ghere
               if(rs.next()){
                type=rs.getString(2);
                flr=rs.getString(3);
                rpd=rs.getInt(4);
                acond=rs.getString(5);
                vw=rs.getString(7);
               cdt= rs.getDate(16);
               fn= rs.getString(9);
                            ln=rs.getString(10);
                g=rs.getString(11);

                
               
               rtype.setText(type);
               floor.setText(flr);
               ac.setText(acond);
               view.setText(vw);
               rentpd.setText(""+rpd);
               chkdate.setText(""+cdt);
               fname.setText(fn);
               lname.setText(ln);
                        gen.setText(g);

               
               
               }
                       //jdatechooser..................thus is to display date in textfield conding u can create a feild and set Text this there SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
                                                                          //      like this field.setText(sdf.format(chooser.getDate()));



               
        }
        catch(Exception e){  
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
      }
      
      
      void days(){
Date d2 = dtc.getDate();                                   //checkin date
long diffdys = d2.getTime() - cdt.getTime();                //diff
             long dys= (long)( diffdys / (1000 * 60 * 60 * 24));                                 //milliseconds to days
                   days.setText(""+dys);
      }
                int rc=0;  //recreational costs

      
      
      
      
    
    public  checkout() {

        initComponents();
        opencon();
                 bg.setBackground(new Color(0,0,0,105));
                 rec.setBackground(new Color(250,250,250));

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cb = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        bg = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rec = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        rectotal = new javax.swing.JTextField();
        swm = new javax.swing.JCheckBox();
        lndry = new javax.swing.JCheckBox();
        gym = new javax.swing.JCheckBox();
        food = new javax.swing.JCheckBox();
        mis = new javax.swing.JCheckBox();
        fname = new javax.swing.JTextField();
        gen = new javax.swing.JTextField();
        chkdate = new javax.swing.JTextField();
        rtype = new javax.swing.JLabel();
        floor = new javax.swing.JLabel();
        ac = new javax.swing.JLabel();
        view = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dtc = new com.toedter.calendar.JDateChooser();
        lname = new javax.swing.JTextField();
        rent = new javax.swing.JLabel();
        days = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        rentpd = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        gtot = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        bill = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ts = new javax.swing.JTextField();

        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Room number");
        add(jLabel2);
        jLabel2.setBounds(330, 40, 180, 22);

        cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select room number" }));
        cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbItemStateChanged(evt);
            }
        });
        cb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbFocusGained(evt);
            }
        });
        cb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbMouseEntered(evt);
            }
        });
        cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActionPerformed(evt);
            }
        });
        cb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbKeyPressed(evt);
            }
        });
        add(cb);
        cb.setBounds(530, 40, 180, 26);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 204));
        jSeparator1.setForeground(new java.awt.Color(255, 102, 102));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setAutoscrolls(true);
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        add(jSeparator1);
        jSeparator1.setBounds(0, 0, 2, 0);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Floor");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("AC");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("View");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("First Name");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Last Name");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Gender");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Checkindate");

        rec.setBorder(javax.swing.BorderFactory.createTitledBorder("Recreation"));

        jLabel14.setText("Total recreational cost");

        rectotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        swm.setText("Swimming(Rs 600)");
        swm.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                swmItemStateChanged(evt);
            }
        });

        lndry.setText("Laundry(Rs 400)");
        lndry.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lndryItemStateChanged(evt);
            }
        });

        gym.setText("Gym(Rs 1000)");
        gym.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                gymItemStateChanged(evt);
            }
        });
        gym.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gymActionPerformed(evt);
            }
        });

        food.setText("Food(Rs.500)");
        food.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                foodItemStateChanged(evt);
            }
        });

        mis.setText("Miscellaneous (Varies)");
        mis.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                misItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout recLayout = new javax.swing.GroupLayout(rec);
        rec.setLayout(recLayout);
        recLayout.setHorizontalGroup(
            recLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recLayout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rectotal, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(recLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(recLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(food)
                    .addComponent(gym)
                    .addComponent(mis)
                    .addComponent(lndry)
                    .addComponent(swm))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        recLayout.setVerticalGroup(
            recLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recLayout.createSequentialGroup()
                .addComponent(swm)
                .addGap(2, 2, 2)
                .addComponent(lndry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gym)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(food)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)
                .addComponent(mis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(recLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(rectotal)))
        );

        fname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        gen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genActionPerformed(evt);
            }
        });

        chkdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chkdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkdateActionPerformed(evt);
            }
        });

        rtype.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rtype.setForeground(new java.awt.Color(255, 255, 255));

        floor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        floor.setForeground(new java.awt.Color(255, 255, 255));

        ac.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ac.setForeground(new java.awt.Color(204, 204, 204));

        view.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        view.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Room type");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Number of days");

        lname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        rent.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        rent.setForeground(new java.awt.Color(255, 255, 255));

        days.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        days.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Total Rent");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("RentPerDay");

        rentpd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rentpd.setForeground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Grand Total(Rent+Other costs)");

        gtot.setEditable(false);
        gtot.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Checkout Date");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel13))
                        .addGap(125, 125, 125)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(floor, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ac, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rtype, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rentpd, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(70, 70, 70)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rent, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(chkdate, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                .addComponent(gen, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                .addComponent(fname, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                .addComponent(lname))
                            .addComponent(days, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gtot, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)))
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(rec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtc, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(168, 168, 168))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(rec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(rtype, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)))
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(floor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ac, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(bgLayout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(jLabel9)))
                                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(bgLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(rentpd, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(3, 3, 3)
                                                .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(bgLayout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel10)
                                                    .addComponent(chkdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)))))
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rent, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dtc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))))
                .addGap(40, 40, 40)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(days, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(gtot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(bg);
        bg.setBounds(40, 90, 1210, 440);

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        add(clear);
        clear.setBounds(420, 560, 120, 50);

        bill.setText("Bill");
        bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billActionPerformed(evt);
            }
        });
        add(bill);
        bill.setBounds(660, 560, 130, 50);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\krithikha\\Desktop\\ip project\\Las-Vegas-HD-Wallpapers-Desktop-Widescreen.jpg")); // NOI18N
        jLabel1.setText("Room number");
        add(jLabel1);
        jLabel1.setBounds(0, 10, 1340, 660);

        ts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsActionPerformed(evt);
            }
        });
        add(ts);
        ts.setBounds(540, 90, 162, 26);
    }// </editor-fold>//GEN-END:initComponents

    private void cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActionPerformed
        // TODO add your handling code here:   opencon();
     
                              
    }//GEN-LAST:event_cbActionPerformed

    private void cbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbItemStateChanged

        // TODO add your handling code here:
    chkout();
        
       
    }//GEN-LAST:event_cbItemStateChanged

    private void cbFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbFocusGained
        // TODO add your handling code here:
      
            if(dtc.getDate()==null)
        dtc.setDate(new Date());
                              try{
        String q="Select * from rinfo where 1status='occupied'";        //make occupied later
        
       Statement stmt =con.createStatement();
               ResultSet rs=stmt.executeQuery(q);
           
 
              while (rs.next()){
                   int r=rs.getInt(1);
                   cb.addItem(""+r);
                   
               }
                       }
        catch(Exception e){            JOptionPane.showMessageDialog(this,e.getMessage());
}
    }//GEN-LAST:event_cbFocusGained

    private void chkdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkdateActionPerformed

    private void cbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbMouseEntered
        // TODO add your handling code here:
        

    }//GEN-LAST:event_cbMouseEntered

    private void tsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tsActionPerformed

    private void genActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genActionPerformed

    private void billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billActionPerformed
        // TODO add your handling code here:
        
            
   days();
       try{
               int c = 0;
              String  rno=(String)cb.getSelectedItem();
                 DateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
                       String d1 = fmt.format(this.dtc.getDate());  

            
        
            int rpd=Integer.parseInt(rentpd.getText());
      int no=Integer.parseInt(days.getText());
      int tot=rpd*no ;
rent.setText(""+tot);

int rcost=Integer.parseInt(rectotal.getText());

int bill=tot+rcost;     //total bill equals the total rent of room + other recreational costs and miscellaneous costs
gtot.setText(""+bill);
 String q2="Update custinfo set status='vacated',checkout_date='"+d1+"',"+"no_of_days="+no+",total_rent="+tot+" where rno='"+rno+"' and status='staying'";

                String q3="Update rinfo set 1status='vacant' where rno='"+rno+"'";
     Statement stmt2=con.createStatement();
                Statement stmt3=con.createStatement();

        stmt2.executeUpdate(q2);
                stmt3.executeUpdate(q3);


             JOptionPane.showMessageDialog(this,"The Total amount to be paid is "+bill);

             JOptionPane.showMessageDialog(this,"Successfuly checked out");

        
        }
        catch(Exception e){    JOptionPane.showMessageDialog(this,e.getMessage());}

    }//GEN-LAST:event_billActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
         if(dtc.getDate()==null)
      dtc.setDate(new Date());
         days();
    }//GEN-LAST:event_formFocusGained

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        rtype.setText("");
        floor.setText("");
        rentpd.setText("");
        view.setText("");
        
                ac.setText("");
                        fname.setText("");
        lname.setText("");
        gen.setText("");
        chkdate.setText("");
        swm.setSelected(false);
        lndry.setSelected(false);
        gym.setSelected(false);
        food.setSelected(false);
        mis.setSelected(false);
rectotal.setText("");
rent.setText("");
days.setText("");
gtot.setText("");
        cb.setSelectedIndex(0);

                
        
    }//GEN-LAST:event_clearActionPerformed

    private void cbKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbKeyPressed
        // TODO add your handling code here:
                  
         

    }//GEN-LAST:event_cbKeyPressed

    private void gymActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gymActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gymActionPerformed

    private void swmItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_swmItemStateChanged
        // TODO add your handling code here:
      
    }//GEN-LAST:event_swmItemStateChanged

    private void lndryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lndryItemStateChanged
        // TODO add your handling code here:
     if(lndry.isSelected())
    rc+=400;
     rectotal.setText(""+rc);
    }//GEN-LAST:event_lndryItemStateChanged

    private void gymItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_gymItemStateChanged
        // TODO add your handling code here:
        
if(gym.isSelected())
    rc+=1000;
rectotal.setText(""+rc);
    }//GEN-LAST:event_gymItemStateChanged

    private void foodItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_foodItemStateChanged
        // TODO add your handling code here:
       if(food.isSelected())
    rc+=500;
rectotal.setText(""+rc);
    }//GEN-LAST:event_foodItemStateChanged

    private void misItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_misItemStateChanged
        // TODO add your handling code here:
        if(mis.isSelected()){
      String m=  JOptionPane.showInputDialog(this,"Enter miscellaneous charges-");
      int mn=Integer.parseInt(m);
    int r1=rc+mn;
      rectotal.setText(""+r1);}
    }//GEN-LAST:event_misItemStateChanged

    public static void main(String[] args){}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ac;
    private javax.swing.JPanel bg;
    private javax.swing.JButton bill;
    private javax.swing.JComboBox<String> cb;
    private javax.swing.JTextField chkdate;
    private javax.swing.JButton clear;
    private javax.swing.JLabel days;
    private com.toedter.calendar.JDateChooser dtc;
    private javax.swing.JLabel floor;
    private javax.swing.JTextField fname;
    private javax.swing.JCheckBox food;
    private javax.swing.JTextField gen;
    private javax.swing.JTextField gtot;
    private javax.swing.JCheckBox gym;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lname;
    private javax.swing.JCheckBox lndry;
    private javax.swing.JCheckBox mis;
    private javax.swing.JPanel rec;
    private javax.swing.JTextField rectotal;
    private javax.swing.JLabel rent;
    private javax.swing.JLabel rentpd;
    private javax.swing.JLabel rtype;
    private javax.swing.JCheckBox swm;
    private javax.swing.JTextField ts;
    private javax.swing.JLabel view;
    // End of variables declaration//GEN-END:variables
}
