/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package krithikha;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author krithikha
 */
public class loginn extends javax.swing.JFrame {
    int x=0,y=100;
    public void paint(Graphics g)
    {super.paint(g);
    Graphics2D g2=(Graphics2D)g;
    Font f=new Font("Georgia Pro Cond Black",Font.BOLD,50);
    g2.setFont(f);
    g2.setColor(Color.WHITE);
    g2.drawString("Hotel Phoenix ",x,y);// for moving text coding
    try{Thread.sleep(50);}
    catch(Exception e){}
    x+=10;
    if(x>this.getWidth())
    x=0;
    repaint();}
    
    
    
    
    Connection con;
    void opencon(){
        try{
            Class.forName("java.sql.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/hotel","root","pass");
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        }
    
    
    
    
    String login(String u,String pwd){
        String q="";
    try{ String c="Select * from pwd";
            if(u.equals("")||pwd.equals(""))
            {q="";}
                
            else{     
            Statement st=con.createStatement();
            ResultSet  rs=st.executeQuery(c);

            while(rs.next()){
                String   a=rs.getString("username");
                String p=rs.getString("password");

                if(a.equalsIgnoreCase(u) && p.equalsIgnoreCase(pwd)){
                     q="yes";
                   
                    break; }
                else 
                    q="Your username and password do not match. Please try again.";
                    
                }
            }       
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(this,"Error in connection");

        }
     return q;   }
    

    /**
     * Creates new form loginn
     */
   public loginn() {
        initComponents();
        plogin.setBackground(new Color(0,0,0,105));
       
    }
      
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        change = new javax.swing.JButton();
        eye = new javax.swing.JToggleButton();
        pass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("flogin");
        setBackground(new java.awt.Color(102, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        plogin.setBackground(new java.awt.Color(102, 102, 102));
        plogin.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Verdana Pro Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("LOGIN");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("Password");

        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        change.setText("Change password");
        change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeActionPerformed(evt);
            }
        });

        eye.setIcon(new javax.swing.ImageIcon("C:\\Users\\krithikha\\Desktop\\ip project\\eye.jpg")); // NOI18N
        eye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eyeActionPerformed(evt);
            }
        });

        pass.setEchoChar('\u2022');
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ploginLayout = new javax.swing.GroupLayout(plogin);
        plogin.setLayout(ploginLayout);
        ploginLayout.setHorizontalGroup(
            ploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ploginLayout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(change)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ploginLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(ploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(login)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(ploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ploginLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ploginLayout.createSequentialGroup()
                        .addGroup(ploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ploginLayout.createSequentialGroup()
                                .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(eye, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 25, Short.MAX_VALUE))))
        );
        ploginLayout.setVerticalGroup(
            ploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ploginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(41, 41, 41)
                .addGroup(ploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(ploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(ploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eye, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(ploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(change)
                    .addComponent(login))
                .addGap(55, 55, 55))
        );

        getContentPane().add(plogin);
        plogin.setBounds(230, 120, 440, 300);

        jLabel1.setBackground(new java.awt.Color(153, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\krithikha\\Desktop\\ip project\\bggg.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 10, 940, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
      opencon();
    }//GEN-LAST:event_formWindowOpened

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:\
        String u=user.getText();
            String pwd=new String(pass.getPassword());
          String  q=login(u,pwd);
          if(q.equals(""))
              JOptionPane.showMessageDialog(null,"Please enter your username and password to login");
           else  if (q!="yes")
                    JOptionPane.showMessageDialog(this,q);
             else if(q.equals("yes")){
                  main frame=new main();
                    frame.setVisible(true);
                    this.dispose();}

    }//GEN-LAST:event_loginActionPerformed

    private void eyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eyeActionPerformed
        // TODO add your handling code here:
        if(eye.isSelected()){
        pass.setEchoChar((char)0);
        ImageIcon img=new ImageIcon("C:\\Users\\krithikha\\Desktop\\ip project\\closeeye.jpg");
        eye.setIcon(img);}
        else{
        pass.setEchoChar('•');
        ImageIcon img=new ImageIcon("C:\\Users\\krithikha\\Desktop\\ip project\\eye.jpg");
        eye.setIcon(img);
        }
    }//GEN-LAST:event_eyeActionPerformed

    private void changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeActionPerformed
        // TODO add your handling code here:
     
        try{
        String nw;
        String confirm;
        String query;
         String u=user.getText();
            String pwd=new String(pass.getPassword());
        String q=login(u,pwd);
      
         if(q.equals("")){
           JOptionPane.showMessageDialog(null,"Enter your username and password in the feilds");}
        else if(q!=("yes")){
           JOptionPane.showMessageDialog(null,"Your username and password do not match. You need to enter correct information to reset your password");}
        else if (q.equals("yes")){
           nw=  JOptionPane.showInputDialog(null,"Enter new password");
        confirm=JOptionPane.showInputDialog(null,"Confirm your password");
                if(nw.equals(confirm))
                {
                    query="Update pwd set password='"+nw+"'where username='"+u+"'";
                    Statement stmt=con.createStatement();
                    stmt.executeUpdate(query);
                    
                 JOptionPane.showMessageDialog(null,"Your password is changed");

                }
                else 
                    JOptionPane.showMessageDialog(null,"The password and its confirmation do not match");
        }}
        catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage());}
                
        
        
        
    }//GEN-LAST:event_changeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 try{
                    Thread.sleep(5000);
                }catch(Exception e){}                
               
                new loginn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton change;
    private javax.swing.JToggleButton eye;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField pass;
    private javax.swing.JPanel plogin;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
