/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package krithikha;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;


import javax.swing.JOptionPane;


/**
 *
 * @author krithikha
 */
public class main extends javax.swing.JFrame {
int x=0,y=200;
   public void paint(Graphics g)
   {super.paint(g);
    Graphics2D g2=(Graphics2D)g;
    Font f=new Font("Georgia Pro Cond Black",Font.BOLD,80);
    g2.setFont(f);
    g2.setColor(Color.WHITE);
    g2.drawString("Hotel PHEONIX",x,y);// for moving text coding
    try{Thread.sleep(50);}
    catch(Exception e){}
    x+=10;
    if(x>this.getWidth())
    x=0;
    repaint();}
    
 
   
        
    /*     
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        roominfo = new javax.swing.JButton();
        checkout = new javax.swing.JButton();
        report = new javax.swing.JButton();
        update = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        checkout1 = new krithikha.checkout();
        home = new javax.swing.JPanel();
        update1 = new krithikha.update();
        roominfo1 = new krithikha.roominfo();
        report1 = new krithikha.report();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel Management ");
        setMaximumSize(new java.awt.Dimension(2000, 2000));
        setMinimumSize(new java.awt.Dimension(1000, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 0, 51));

        roominfo.setBackground(new java.awt.Color(0, 153, 153));
        roominfo.setText("<html><body align=center>\nRoom information \n<br>\nand\n<br>\nCheck IN\n</body>\n</html>");
        roominfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roominfoActionPerformed(evt);
            }
        });

        checkout.setBackground(new java.awt.Color(0, 153, 153));
        checkout.setText("Check out");
        checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutActionPerformed(evt);
            }
        });

        report.setBackground(new java.awt.Color(0, 153, 153));
        report.setText("Report");
        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(0, 153, 153));
        update.setText("Update Room Info");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(0, 153, 153));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(0, 153, 153));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roominfo)
            .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
            .addComponent(report, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(checkout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(roominfo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(checkout, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(report, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 160, 240, 630);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.CardLayout());
        jPanel2.add(checkout1, "card6");

        home.setMaximumSize(new java.awt.Dimension(45000, 45000));
        home.setOpaque(false);

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        jPanel2.add(home, "card3");
        jPanel2.add(update1, "card7");
        jPanel2.add(roominfo1, "card6");
        jPanel2.add(report1, "card6");

        getContentPane().add(jPanel2);
        jPanel2.setBounds(240, 160, 1170, 610);

        jLabel2.setBackground(new java.awt.Color(153, 0, 51));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1420, 160);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\krithikha\\Desktop\\ip project\\Las-Vegas-HD-Wallpapers-Desktop-Widescreen.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-20, 0, 1440, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jPanel2.removeAll();                    
       jPanel2.repaint();                   
       jPanel2.revalidate();                
               jPanel2.add(home);                 
               jPanel2.repaint();
       jPanel2.revalidate();
        
        
        
        

    }//GEN-LAST:event_formWindowOpened

    private void roominfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roominfoActionPerformed
        // TODO add your handling code here:
   jPanel2.removeAll();                    // this is for connectying
                      //check the code meaning and usage
               jPanel2.add(roominfo1);                 
               jPanel2.repaint();
       jPanel2.revalidate();
        
        
        
        
        
    }//GEN-LAST:event_roominfoActionPerformed

    private void checkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutActionPerformed
        // TODO add your handling code here:
        
          jPanel2.removeAll();
       jPanel2.repaint();
       jPanel2.revalidate();
               jPanel2.add(checkout1);
               jPanel2.repaint();
       jPanel2.revalidate();

    }//GEN-LAST:event_checkoutActionPerformed

    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed
        // TODO add your handling code here:
        jPanel2.removeAll();
       jPanel2.repaint();                   //works after  being removed also .check.
       jPanel2.revalidate();                //check the code meaning and usage
               jPanel2.add(report1);                 
               jPanel2.repaint();
       jPanel2.revalidate();
    }//GEN-LAST:event_reportActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        jPanel2.removeAll();
       jPanel2.repaint();                   //works after  being removed also .check.
       jPanel2.revalidate();                //check the code meaning and usage
               jPanel2.add(update1);                 
               jPanel2.repaint();
       jPanel2.revalidate();
       
       
    }//GEN-LAST:event_updateActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
 jPanel2.removeAll();
   jPanel2.repaint();                   //works after  being removed also .check.
       jPanel2.revalidate();                //check the code meaning and usage
               jPanel2.add(home);                 
               jPanel2.repaint();
       jPanel2.revalidate();
       
        
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public  void run() {
                new main().setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton checkout;
    private krithikha.checkout checkout1;
    private javax.swing.JButton exit;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton report;
    private krithikha.report report1;
    private javax.swing.JButton roominfo;
    private krithikha.roominfo roominfo1;
    private javax.swing.JButton update;
    private krithikha.update update1;
    // End of variables declaration//GEN-END:variables
}
