/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package krithikha;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author krithikha
 */
public class report extends javax.swing.JPanel {
 Connection con;
    void opencon(){
        try{
            Class.forName("java.sql.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/hotel","root","pass");
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        }
    
    
    String dt1,dt2;
  void find(String d1,String d2){
  try{
     String q="Select * from rinfo natural join custinfo where checkinDate between '"+d1+"' and '"+d2+"' ";
  Statement stmt=con.createStatement();
ResultSet rs=stmt.executeQuery(q);
DefaultTableModel dtm=(DefaultTableModel)report.getModel();
while(dtm.getRowCount()>0)
dtm.removeRow(0);
String id,f,rno,rt,a,r,b,c,v;

int rent;
while(rs.next()){
r=rs.getString(1);         //rno
id=rs.getString(2);                //rtype
f=rs.getString(3); //floor
rent=rs.getInt(4);       //rent of room
rt=rs.getString(5);         //ac
a=rs.getString(6);          //1status
v=rs.getString(7);                  //view from room
b=rs.getString(9);    //fname
c=rs.getString(12); //nationality
 

Object nr[]={r,id,f,rt,v,a,b,c,rent,};
dtm.addRow(nr);}

int p=0; 
String q2="Select sum(rentperday) from custinfo where checkindate between '"+dt1+"' and '"+dt2+"'";
Statement stmt2=con.createStatement();
ResultSet rs2=stmt.executeQuery(q2);
while(rs2.next())
     p=rs2.getInt(1);
profit.setText(""+p);
int n=report.getRowCount();
rep.setText("Number of customers checked in at this period is= "+n+" and the profit earned is="+p);
  }
   catch(Exception e){
JOptionPane.showMessageDialog(this,e.getMessage());
  }
     
  }
    /**
     * Creates new form report1
     */
    public report() {
        opencon();
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        find = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        report = new javax.swing.JTable();
        from = new com.toedter.calendar.JDateChooser();
        to = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        profit = new javax.swing.JTextField();
        rep = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(100, 100));
        setLayout(null);

        find.setText("Find details about customers ");
        find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findActionPerformed(evt);
            }
        });
        add(find);
        find.setBounds(652, 74, 300, 29);

        report.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Roomnumber", "Type", "Floor", "ac", "View", "Status", "Name", "Nationality", "Rent"
            }
        ));
        jScrollPane1.setViewportView(report);

        add(jScrollPane1);
        jScrollPane1.setBounds(100, 220, 880, 220);
        add(from);
        from.setBounds(395, 68, 160, 26);
        add(to);
        to.setBounds(395, 133, 160, 26);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("From");
        add(jLabel1);
        jLabel1.setBounds(260, 70, 65, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 0));
        jLabel4.setText("Total Amount collected");
        add(jLabel4);
        jLabel4.setBounds(410, 520, 220, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("To");
        add(jLabel2);
        jLabel2.setBounds(258, 133, 77, 22);

        clear.setText("clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        add(clear);
        clear.setBounds(770, 140, 65, 29);
        add(profit);
        profit.setBounds(650, 520, 190, 26);

        rep.setBackground(new java.awt.Color(204, 204, 204));
        rep.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        rep.setForeground(new java.awt.Color(255, 255, 255));
        add(rep);
        rep.setBounds(100, 550, 1000, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\krithikha\\Desktop\\ip project\\restaurant_table_interior_modern_style_39288_1920x1080.jpg")); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(2, 0, 1220, 650);
    }// </editor-fold>//GEN-END:initComponents

    private void findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findActionPerformed
        // TODO add your handling code here:
         
         
           DateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
            dt1 = fmt.format(this.from.getDate());
           dt2= fmt.format(this.to.getDate());

find(dt1,dt2);

 






    }//GEN-LAST:event_findActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        from.setCalendar(null);
        to.setCalendar(null);
       report.removeAll();
       profit.setText("");
        
        
    }//GEN-LAST:event_clearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JButton find;
    private com.toedter.calendar.JDateChooser from;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField profit;
    private javax.swing.JLabel rep;
    private javax.swing.JTable report;
    private com.toedter.calendar.JDateChooser to;
    // End of variables declaration//GEN-END:variables
}
